Server Forms Search Boxes
Suprcode/Crystal pull request #1038
Opened 2024-12-28 23:22 UTC by JevLOMCN

Added the following Search Boxes to Forms:

NPCInfoForm
QuestInfoForm
RecipeInfoForm
GameShopForm
MagicInfoForm

![image](https://github.com/user-attachments/assets/4875a2f4-401a-41fb-9a9e-acb5b620fb29)
![image](https://github.com/user-attachments/assets/9e839571-df52-4a48-bd9c-854ea27c11ad)
![image](https://github.com/user-attachments/assets/a8c7b0ce-6534-4d18-9722-6d8212009a03)
![image](https://github.com/user-attachments/assets/13d61137-174f-489b-a5db-6e68521bb00c)
![image](https://github.com/user-attachments/assets/09212775-f143-4b54-b400-b8bfe0273fe6)

2024-12-28 23:41 UTC, Suprcode commented
Form textboxes have a property called "PlaceholderText" - no need to do all that weird fake placeholder logic.

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.textbox.placeholdertext?view=windowsdesktop-9.0

2024-12-29 18:07 UTC, JevLOMCN commented
That should do it @Suprcode

2024-12-30 15:56 UTC, Suprcode requested changes
Changes and alot of tidying needed please

2025-01-16 17:22 UTC, Suprcode requested changes
Still not ideal the way you've implemented the recipe filter

2025-01-16 17:22 UTC, Suprcode commented on Server.MirForms/Database/RecipeInfoForm.cs
> +        {
Doesn't really make sense that this is the only search box you need to press enter on.

Remove all this load logic in to its own method, store the recipeFiles in a public list. then filter on this public list the same way it works in the other forms you've updated.

2025-01-26 16:09 UTC, JevLOMCN commented
https://github.com/Suprcode/Crystal/pull/1038/commits/02dc9164b07459687293fbf4e0c604ab35cf7be0 should fix this @Suprcode

2025-01-27 17:33 UTC, Suprcode requested changes

2025-01-27 17:33 UTC, Suprcode commented on Server.MirForms/Database/RecipeInfoForm.cs
> +            {
Doesn't look to have been corrected yet. As per my previous comments..

Doesn't really make sense that this is the only search box you need to press enter on.

Remove all this load logic in to its own method, store the recipeFiles in a public list. then filter on this public list the same way it works in the other forms you've updated.

2025-01-28 20:52 UTC, merged